apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 8
  selector:
    matchLabels:
      name: nodeapp
  template:
    metadata:
      labels:
        name: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: docker.io/220011/nodeapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
